### ISSUE TITLE
Not able to connect to security and compliance center using the tool

### ISSUE THREAD

**Issue by mjagadeesh408** [OfficeDev/MAMD#8]
When I am providing credentials to connect to security and compliance center PowerShell, it is throwing error saying " There was an issue in connecting to Security & Compliance Center. Please try running the tool again after some time."

![image](https://user-images.githubusercontent.com/95905241/145575298-77a453f5-379d-4e0e-bed8-8d66995d9e06.png)

I tried restarting the system and running the tool, re-installing the tool etc., and still it is not working. The account I am using for logging in have compliance admin, security admin and Global reader roles as well.

**Comment by mjagadeesh408** [comment]
Any help regarding this issue?

**Comment by snehakishore21** [comment]
Can you please share the log file?
Can you please check if you are able to login to Security & Compliance PowerShell or Exchange Online in separate PowerShell window on your machine? 
Once try disconnecting Exchange-Online from everywhere(each PowerShell session) using Disconnect-ExchangeOnline and then try again.

**Comment by snehakishore21** [comment]
> Any help regarding this issue?
Can you please share the log file?
Can you please check if you are able to login to Security & Compliance PowerShell or Exchange Online in separate PowerShell window on your machine?
Once try disconnecting Exchange-Online from everywhere(each PowerShell session) using Disconnect-ExchangeOnline and then try again.

**Comment by tmoen2015** [comment]
I have a customer experiencing the same issue. They are using other commandlets and powershell scripts but this fails. It cannot connect to the Compliance Center and the user was able to run other compliance powershell commands. This custoemr is in GCC.

**Comment by snehakishore21** [comment]
Currently GCC tenants is not supported but to support that you can make few changes in the created PowerShell scripts and retry once:

Please find these two ps1 files:
For both login page, (C:\Users\<Username>\AppData\Local\Temp\MigrationAssistantforMicrosoftDLP\output\Symantec\<Timestamp>\FetchMIPDetails.ps1) and connect&import page (C:\Users\<Username>\AppData\Local\Temp\MigrationAssistantforMicrosoftDLP\output\Symantec\<Timestamp>\Symantec_PsDlpCommands.ps1),

Find the line:
Connect-IPPSSession -UserPrincipalName $userName -ErrorAction:SilentlyContinue -WarningAction:SilentlyContinue

and replace this with:
$ConnectionUri = 'https://l5.ps.compliance.protection.office365.us/powershell-liveid/'  (for O365USGovDoD)
$ConnectionUri = 'https://ps.compliance.protection.office365.us/powershell-liveid/' (for O365USGovGCCHigh)

Connect-IPPSSession -UserPrincipalName $userName -ConnectionUri $ConnectionUri -ErrorAction:SilentlyContinue -WarningAction:SilentlyContinue


Please try this once and let us know if this works.
